FROM adoptopenjdk:11-jre-hotspot

ENV SONAR_VERSION=9.1.0.47736

RUN set -x \
  && apt-get update \
  && apt-get install -y gnupg2 unzip \
  && curl -o sonarqube.zip -fSL https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-${SONAR_VERSION}.zip \
  && unzip sonarqube.zip -d /opt \
  && mv /opt/sonarqube-${SONAR_VERSION} /opt/sonarqube \
  && groupadd -r sonarqube \
  && useradd -r -g sonarqube sonarqube \
  && rm sonarqube.zip* \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/sonarqube

RUN chmod -R 0770 logs temp data extensions \
  && chown -R sonarqube:sonarqube logs temp data extensions

USER sonarqube

ENTRYPOINT ["./bin/linux-x86-64/sonar.sh"]
CMD ["start"]
